export const TRAVEL_HELLO_WORLD_BEGIN = 'TRAVEL_HELLO_WORLD_BEGIN';
export const TRAVEL_HELLO_WORLD_SUCCESS = 'TRAVEL_HELLO_WORLD_SUCCESS';
export const TRAVEL_HELLO_WORLD_FAILURE = 'TRAVEL_HELLO_WORLD_FAILURE';
export const TRAVEL_HELLO_WORLD_DISMISS_ERROR = 'TRAVEL_HELLO_WORLD_DISMISS_ERROR';
